/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bth5_c2;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author 84346
 */
public class KhamBenh extends javax.swing.JFrame {

    /**
     * Creates new form KhamBenh
     */
    public KhamBenh() {
        initComponents();
        addCBBS();
        TbDV.setDefaultEditor(Object.class, null);
        NgayKham.getDateEditor().getUiComponent().addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent evt) {
                NgayKhamKeyPressed(evt);
            }
        });
        TaoTableDV();
    }
    DefaultTableModel tbModelDV = new DefaultTableModel();
    public void TaoTableDV(){
        String tieuDe[] = {"Ma dich vu","Ten dich vu","Don gia"};
        tbModelDV.setColumnIdentifiers(tieuDe);
        
        try{
            Connection conn = BTH5_C2.getMyConnection();
            String strSQL = "Select * from DICHVU";
            String row[] = new String[3];
            PreparedStatement ps = conn.prepareStatement(strSQL);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                row[0] = rs.getString(1);
                row[1] = rs.getString(2);
                row[2] = rs.getString(3);
                tbModelDV.addRow(row);
            }
        }catch(Exception e){
            System.out.print(e);
        }
        
        TbDV.setModel(tbModelDV);
        
        TableColumnModel tcm = TbDV.getColumnModel();
        //column1
        tcm.getColumn(0).setWidth(0);
        tcm.getColumn(0).setMinWidth(0);
        tcm.getColumn(0).setMaxWidth(0); 
        //column3
        tcm.getColumn(2).setWidth(0);
        tcm.getColumn(2).setMinWidth(0);
        tcm.getColumn(2).setMaxWidth(0); 
        //System.out.println(TbDV.getModel().getValueAt(TbDV.getSelectedRow(),1));
        setVisible(true);
    }
    
    private void NgayKhamKeyPressed(KeyEvent evt)
    {
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            YeuCauKham.setText("");
            DefaultComboBoxModel cbm = new DefaultComboBoxModel();
            Object item = CBTenBS.getSelectedItem();
            String MaBS = ((BacSi)item).getMaBS();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(this.NgayKham.getDate());
            try{
            Connection conn = BTH5_C2.getMyConnection();
            String SQL = "Select KB.MABN, BN.TENBN from BENHNHAN BN, KHAMBENH KB "
                    + "where KB.MABS = ? AND KB.NGAYKHAM = ? AND KB.THANHTOAN = 0;";
            
            PreparedStatement ps = conn.prepareStatement(SQL);
            ps.setString(1, MaBS);
            ps.setString(2, date);
            
            ResultSet rs = ps.executeQuery();
            
            while(rs.next())
            {
                String MaBN = rs.getString(1);
                String TenBN = rs.getString(2);
                cbm.addElement(new BenhNhan(MaBN, TenBN));
            }
            CBTenBN.setModel(cbm);
        }catch(Exception e)
        {
            System.out.print(e);
        }
        }
    }
    
    public void addCBBS()
    {
        DefaultComboBoxModel cbm = new DefaultComboBoxModel();
        
        try{
            Connection conn = BTH5_C2.getMyConnection();
            String SQL = "Select * from BACSI";
            
            PreparedStatement ps = conn.prepareStatement(SQL);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next())
            {
                String MaBS = rs.getString(1);
                String TenBS = rs.getString(2);
                cbm.addElement(new BacSi(MaBS, TenBS));
            }
            
            CBTenBS.setModel(cbm);
            
        }catch(Exception e)
        {
            System.out.print(e);
        }
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CBTenBN = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        CBTenBS = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        YeuCauKham = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        KetLuan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbDV = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBDVBS = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        Them = new javax.swing.JButton();
        NgayKham = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chi tiet kham benh");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("BS");

        CBTenBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBTenBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTenBNActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên BN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ngày khám");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("YC khám");

        YeuCauKham.setEditable(false);
        YeuCauKham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("KL");

        KetLuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KetLuan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KetLuanKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("DS Dịch vụ");

        TbDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TbDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên DV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbDVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbDV);

        TBDVBS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TBDVBS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên DV", "SL"
            }
        ));
        jScrollPane2.setViewportView(TBDVBS);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("DS Dịch vụ BS chọn");

        Them.setText("Thêm");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        NgayKham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Khám bệnh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(130, 130, 130)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(30, 30, 30))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(CBTenBN, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(CBTenBS, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(KetLuan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(YeuCauKham, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(CBTenBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(NgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBTenBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(YeuCauKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(KetLuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(Them, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        // TODO add your handling code here:
        Object item = CBTenBS.getSelectedItem();
        String MaBS = ((BacSi)item).getMaBS(); 
        Object item1 = CBTenBN.getSelectedItem();
        String MaBN = ((BenhNhan)item1).getMaBN(); 
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(this.NgayKham.getDate());
        String ketLuan = this.KetLuan.getText();
        String MaDV[] = new String[20];
        int SoLuong[] = new int[20];
        int ThanhTien[] = new int[20];
        String MaKB = "";
        
        try{
            Connection conn = BTH5_C2.getMyConnection();
            String SQL1 = "Update KHAMBENH SET KETLUAN = ?"
                    + "WHERE MABS = ? AND MABN = ? AND NGAYKHAM = ?";
            
            String SQL2 = "SELECT MAKB FROM KHAMBENH "
                    + "WHERE MABS = ? AND MABN = ? AND NGAYKHAM = ?";
            
            String SQL3 = "Insert into THUPHI values (?,?,?,?)";
            
            PreparedStatement ps1 = conn.prepareStatement(SQL1);
            PreparedStatement ps2 = conn.prepareStatement(SQL2);
            PreparedStatement ps3 = conn.prepareStatement(SQL3);
            
            ps1.setString(1,ketLuan);
            ps1.setString(2,MaBS);
            ps1.setString(3,MaBN);
            ps1.setString(4,date);
            
            ps2.setString(1, MaBS);
            ps2.setString(2, MaBN);
            ps2.setString(3, date);
            
            int rs1 = ps1.executeUpdate();
            ResultSet rs2 = ps2.executeQuery();
            int rs3=0; 
            
            if(rs2.next())
            {
                MaKB = rs2.getString(1);
            }
            System.out.print(MaKB);
            
            int size = TBDVBS.getModel().getRowCount();
            
            for(int i = 0;i<size;i++)
            {
                MaDV[i] = TBDVBS.getModel().getValueAt(i, 0).toString();
                SoLuong[i] = Integer.parseInt(TBDVBS.getModel().getValueAt(i, 2).toString());
                int DonGia = Integer.parseInt(TBDVBS.getModel().getValueAt(i, 3).toString());
                ThanhTien[i] = DonGia*SoLuong[i];
            }
            
            for(int i = 0;i<size;i++)
            {
                ps3.setString(1, MaKB);
                ps3.setString(2, MaDV[i]);
                ps3.setInt(3, SoLuong[i]);
                ps3.setInt(4, ThanhTien[i]);
                rs3 = ps3.executeUpdate();
            }
            
            if(rs1 >= 1 && rs3>=1)
            {
                JOptionPane.showMessageDialog(this, "Them thanh cong");
            }     
            else
            {
                JOptionPane.showMessageDialog(this, "Them that bai");
            }
        }catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_ThemActionPerformed

    
    private void KetLuanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KetLuanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_KetLuanKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void CBTenBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTenBNActionPerformed
        // TODO add your handling code here:
        Object item = CBTenBN.getSelectedItem();
        String MaBN = ((BenhNhan)item).getMaBN();
        Object item1 = CBTenBS.getSelectedItem();
        String MaBS = ((BacSi)item1).getMaBS();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(this.NgayKham.getDate());     
        
        try{
            Connection conn = BTH5_C2.getMyConnection();
            String SQL = "Select YEUCAUKHAM from KHAMBENH "
                    + "where MABS = ? AND NGAYKHAM = ? AND MABN = ?";
            
            PreparedStatement ps = conn.prepareStatement(SQL);
            ps.setString(1, MaBS);
            ps.setString(2, date);
            ps.setString(3, MaBN);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next())
            {
                String KetLuan = rs.getString(1);
                YeuCauKham.setText(KetLuan);
            }
        }catch(Exception e)
        {
            System.out.print(e);
        }
    }//GEN-LAST:event_CBTenBNActionPerformed

    private void TbDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbDVMouseClicked
        // TODO add your handling code here:
        String tieuDe[] = {"Ma dich vu","Ten dich vu","So luong","Don gia"};  
        int column0 = 0;
        int column1 = 1;
        int column2 = 2;
        int row = TbDV.getSelectedRow();
        String MaDV = TbDV.getModel().getValueAt(row, column0).toString();
        String TenDV = TbDV.getModel().getValueAt(row, column1).toString();
        String DonGia = TbDV.getModel().getValueAt(row, column2).toString();
        tbModelDVBS.setColumnIdentifiers(tieuDe);
        tbModelDV.removeRow(row);
        
        String rowModel[] = new String[4];
        rowModel[0] = MaDV;
        rowModel[1] = TenDV;
        rowModel[2] = "1";
        rowModel[3] = DonGia;
        tbModelDVBS.addRow(rowModel);
        TBDVBS.setModel(tbModelDVBS);
        
        TableColumnModel tcm = TBDVBS.getColumnModel();
        //column1
        tcm.getColumn(0).setWidth(0);
        tcm.getColumn(0).setMinWidth(0);
        tcm.getColumn(0).setMaxWidth(0); 
        //column4
        tcm.getColumn(3).setWidth(0);
        tcm.getColumn(3).setMinWidth(0);
        tcm.getColumn(3).setMaxWidth(0); 
    }//GEN-LAST:event_TbDVMouseClicked

    private DefaultTableModel tbModelDVBS = new DefaultTableModel();
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhamBenh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhamBenh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBTenBN;
    private javax.swing.JComboBox<String> CBTenBS;
    private javax.swing.JTextField KetLuan;
    private com.toedter.calendar.JDateChooser NgayKham;
    private javax.swing.JTable TBDVBS;
    private javax.swing.JTable TbDV;
    private javax.swing.JButton Them;
    private javax.swing.JTextField YeuCauKham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
