/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bth5_c2;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author 84346
 */
public class ThanhToan extends javax.swing.JFrame {

    /**
     * Creates new form ThanhToan
     */
    public ThanhToan() {
        initComponents();
        NgayKham.getDateEditor().getUiComponent().addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent evt) {
                NgayKhamKeyPressed(evt);
            }
        });
    }
    
    private void NgayKhamKeyPressed(KeyEvent evt)
    {
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String tieuDe[] = {"Ten dich vu","So Luong","Thanh Tien"};
            DefaultTableModel tbModelDV = new DefaultTableModel();
            tbModelDV.setColumnIdentifiers(tieuDe);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(this.NgayKham.getDate());
            String MaBN = this.MaBN.getText();
            
            String ThanhToan = "";
            try{
            String rowModel[] = new String[3];
            Connection conn = BTH5_C2.getMyConnection();
            
            String SQL1 = "Select MAKB, YEUCAUKHAM, KETLUAN, THANHTOAN from KHAMBENH "
                    + "where MABN = ? AND NGAYKHAM = ?";
            
            String SQL2 = "Select DV.TENDV, TP.SOLUONG, TP.THANHTIEN from THUPHI TP, DICHVU DV "
                    + "where TP.MAKB = ? AND DV.MADV = TP.MADV";
            
            PreparedStatement ps1 = conn.prepareStatement(SQL1);
            PreparedStatement ps2 = conn.prepareStatement(SQL2);
            
            System.out.println(MaBN + date);
            
            ps1.setString(1, MaBN);
            ps1.setString(2, date);
            
            
            ResultSet rs1 = ps1.executeQuery();
            
            
            if(rs1.next())
            {
                MaKB = rs1.getString(1);
                System.out.println(MaKB);
                String YeuCauKham = rs1.getString(2);
                String KetLuan = rs1.getString(3);
                ThanhToan = rs1.getString(4);
                YEUCAUKHAM.setText(YeuCauKham);
                KETLUAN.setText(KetLuan);
                if(Integer.parseInt(ThanhToan) == 1)
                {
                    AlreadyPaid.setSelected(true);
                    TTBtn.setEnabled(false);
                }
                else
                {
                    AlreadyPaid.setSelected(false);
                    TTBtn.setEnabled(true);
                }
            }
            
            System.out.print(ThanhToan);
            
            ps2.setString(1, MaKB);
            ResultSet rs2 = ps2.executeQuery();
            
            while(rs2.next())
            {
                rowModel[0] = rs2.getString(1);
                rowModel[1] = rs2.getString(2);
                rowModel[2] = rs2.getString(3);
                tbModelDV.addRow(rowModel);
            }
            TBDV.setModel(tbModelDV);
            
            int TongTien = 0;
            int column = 2;
            int size = TBDV.getRowCount();
            for(int i =0; i < size; i++)
            {
                int ThanhTien = Integer.parseInt(TBDV.getModel().getValueAt(i, column).toString());
                TongTien = TongTien + ThanhTien;
            }
            TONGTIEN.setText(String.valueOf(TongTien));

        }catch(Exception e)
        {
            System.out.print(e);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        NgayKham = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        MaBN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TenBN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        KETLUAN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        YEUCAUKHAM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TONGTIEN = new javax.swing.JTextField();
        AlreadyPaid = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TBDV = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        TTBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thanh toan kham benh");
        setResizable(false);

        NgayKham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã BN");

        MaBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MaBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MaBNKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên BN");

        TenBN.setEditable(false);
        TenBN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TenBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenBNActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("DV đã khám");

        KETLUAN.setEditable(false);
        KETLUAN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("YC khám");

        YEUCAUKHAM.setEditable(false);
        YEUCAUKHAM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tổng tiền");

        TONGTIEN.setEditable(false);
        TONGTIEN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        AlreadyPaid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AlreadyPaid.setText("Đã thanh toán");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("KL");

        TBDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TBDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên DV", "SL", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TBDV);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày khám");

        TTBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TTBtn.setText("Thanh toán");
        TTBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TTBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Thanh toán");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TenBN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaBN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KETLUAN, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(AlreadyPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TONGTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(YEUCAUKHAM, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(TTBtn)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(MaBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TenBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NgayKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(YEUCAUKHAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TONGTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(KETLUAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(AlreadyPaid))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(TTBtn)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TenBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenBNActionPerformed

    private void TTBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TTBtnActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = BTH5_C2.getMyConnection();
            String SQL = "Update KHAMBENH "
                    + "set THANHTOAN = '1' "
                    + "where MAKB = ?";
            
            PreparedStatement ps = conn.prepareStatement(SQL);
            ps.setString(1, MaKB);
            
            int rs = ps.executeUpdate();
            if(rs >= 1)
            {
                AlreadyPaid.setSelected(true);
                TTBtn.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Thanh toan thanh cong");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Thanh toan that bai");
            }
        }catch(Exception e)
        {
            System.out.print(e);
        }
        
    }//GEN-LAST:event_TTBtnActionPerformed

    private void MaBNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaBNKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String MaBN = this.MaBN.getText();
            try{
            Connection conn = BTH5_C2.getMyConnection();
            String SQL = "Select TENBN from BENHNHAN where MABN = ?";
            
            PreparedStatement ps = conn.prepareStatement(SQL);
            ps.setString(1, MaBN);
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next())
            {
                String tenBN = rs.getString(1);
                TenBN.setText(tenBN);
            }
            
        }catch(Exception e)
        {
            System.out.print(e);
        }
        }
    }//GEN-LAST:event_MaBNKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThanhToan().setVisible(true);
            }
        });
    }
    String MaKB = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AlreadyPaid;
    private javax.swing.JTextField KETLUAN;
    private javax.swing.JTextField MaBN;
    private com.toedter.calendar.JDateChooser NgayKham;
    private javax.swing.JTable TBDV;
    private javax.swing.JTextField TONGTIEN;
    private javax.swing.JButton TTBtn;
    private javax.swing.JTextField TenBN;
    private javax.swing.JTextField YEUCAUKHAM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
